import { prisma } from "@/lib/prisma";

/**
 * Action Plan Auto-Generator
 *
 * Analyzes AI segmentation results and generates recommended marketing
 * action plans for each segment. Plans include email campaigns, SMS campaigns,
 * discount offers, loyalty rewards, and personal outreach.
 */

export interface ActionItem {
  id: string;
  type:
    | "EMAIL_CAMPAIGN"
    | "SMS_CAMPAIGN"
    | "DISCOUNT_OFFER"
    | "LOYALTY_REWARD"
    | "PERSONAL_OUTREACH";
  title: string;
  description: string;
  channel: "email" | "sms" | "both";
  priority: "HIGH" | "MEDIUM" | "LOW";
  timing: "IMMEDIATE" | "WITHIN_3_DAYS" | "WITHIN_7_DAYS" | "WITHIN_14_DAYS";
  template: {
    subject?: string;
    body: string;
    discountType?: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_SHIPPING";
    discountValue?: number;
  };
  status: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "SKIPPED";
  campaignId?: string | null;
  completedAt?: string | null;
}

export interface ActionPlanData {
  segmentId: string;
  segmentType: string;
  name: string;
  description: string;
  actions: ActionItem[];
  priority: "HIGH" | "MEDIUM" | "LOW";
  status: string;
  isAutoGenerated: boolean;
  estimatedImpact: {
    revenueUplift: string;
    customerRetention: string;
    engagement: string;
  };
}

export class ActionPlanService {
  /**
   * Generate action plans for all AI segments in an organization
   */
  static async generateForOrganization(
    organizationId: string,
  ): Promise<{ generated: number; updated: number }> {
    const segments = await prisma.segment.findMany({
      where: {
        organizationId,
        isAiPowered: true,
        customerCount: { gt: 0 },
      },
    });

    let generated = 0;
    let updated = 0;

    for (const segment of segments) {
      if (!segment.segmentType) continue;

      const plan = this.generatePlanForSegment(segment);
      if (!plan) continue;

      // Check if a plan already exists for this segment
      const existing = await prisma.actionPlan.findFirst({
        where: {
          segmentId: segment.id,
          organizationId,
          isAutoGenerated: true,
        },
      });

      if (existing) {
        // Preserve manually completed/skipped action statuses
        const existingActions = (existing.actions as ActionItem[]) || [];
        const completedIds = existingActions
          .filter((a) => a.status === "COMPLETED" || a.status === "SKIPPED")
          .map((a) => a.id);

        const mergedActions = plan.actions.map((action) => {
          if (completedIds.includes(action.id)) {
            const old = existingActions.find((a) => a.id === action.id);
            return old || action;
          }
          return action;
        });

        await prisma.actionPlan.update({
          where: { id: existing.id },
          data: {
            name: plan.name,
            description: plan.description,
            actions: mergedActions as any,
            priority: plan.priority,
            estimatedImpact: plan.estimatedImpact as any,
            actionsTotal: mergedActions.length,
            actionsCompleted: mergedActions.filter(
              (a) => a.status === "COMPLETED",
            ).length,
            generatedAt: new Date(),
          },
        });
        updated++;
      } else {
        await prisma.actionPlan.create({
          data: {
            segmentId: segment.id,
            organizationId,
            name: plan.name,
            description: plan.description,
            actions: plan.actions as any,
            priority: plan.priority,
            status: "DRAFT",
            isAutoGenerated: true,
            actionsTotal: plan.actions.length,
            actionsCompleted: 0,
            estimatedImpact: plan.estimatedImpact as any,
            generatedAt: new Date(),
          },
        });
        generated++;
      }
    }

    return { generated, updated };
  }

  /**
   * Generate a plan for a specific segment based on its type and metrics
   */
  static generatePlanForSegment(segment: any): ActionPlanData | null {
    const type = segment.segmentType;
    const count = segment.customerCount || 0;
    const avgLtv = segment.avgLifetimeValue || 0;
    const avgEng = segment.avgEngagement || 0;

    switch (type) {
      case "CHAMPION":
        return this.buildChampionPlan(segment, count, avgLtv, avgEng);
      case "HIGH_VALUE":
        return this.buildHighValuePlan(segment, count, avgLtv, avgEng);
      case "AT_RISK":
        return this.buildAtRiskPlan(segment, count, avgLtv, avgEng);
      case "ENGAGED":
        return this.buildEngagedPlan(segment, count, avgLtv, avgEng);
      case "NEW":
        return this.buildNewCustomerPlan(segment, count, avgLtv, avgEng);
      case "FREQUENT":
        return this.buildFrequentBuyerPlan(segment, count, avgLtv, avgEng);
      default:
        return null;
    }
  }

  // ──────────────────────────────────────────────
  // SEGMENT-SPECIFIC PLAN BUILDERS
  // ──────────────────────────────────────────────

  private static buildChampionPlan(
    segment: any,
    count: number,
    avgLtv: number,
    avgEng: number,
  ): ActionPlanData {
    return {
      segmentId: segment.id,
      segmentType: "CHAMPION",
      name: `Champion Loyalty & Advocacy Program`,
      description: `${count} champion customers with avg LTV $${avgLtv.toFixed(0)}. Focus on retention, referrals, and increasing order frequency.`,
      priority: "HIGH",
      status: "DRAFT",
      isAutoGenerated: true,
      estimatedImpact: {
        revenueUplift: "15-25%",
        customerRetention: "95%+",
        engagement: "High",
      },
      actions: [
        {
          id: "champion_1",
          type: "EMAIL_CAMPAIGN",
          title: "VIP Thank You & Exclusive Preview",
          description:
            "Send a personalized thank-you email with early access to new products or upcoming sales. Make champions feel their value is recognized.",
          channel: "email",
          priority: "HIGH",
          timing: "IMMEDIATE",
          template: {
            subject: "You're one of our top customers — here's a sneak peek 🎉",
            body: "Thank you for being an incredible customer! As one of our Champions, you get exclusive early access to our newest arrivals before anyone else. Browse your VIP collection now.",
          },
          status: "PENDING",
        },
        {
          id: "champion_2",
          type: "SMS_CAMPAIGN",
          title: "Referral Program Invite",
          description:
            "Invite champions to join a referral program. They're your best advocates — give them a unique referral code with rewards for each friend they bring.",
          channel: "sms",
          priority: "HIGH",
          timing: "WITHIN_3_DAYS",
          template: {
            body: "Hey {firstName}! 🌟 As a valued VIP, share your unique referral link and earn $10 for every friend who orders. Your friends get 10% off too!",
          },
          status: "PENDING",
        },
        {
          id: "champion_3",
          type: "LOYALTY_REWARD",
          title: "Bonus Loyalty Points",
          description:
            "Award bonus loyalty points as a surprise reward. This keeps champions engaged in the loyalty program and incentivizes their next purchase.",
          channel: "both",
          priority: "MEDIUM",
          timing: "WITHIN_7_DAYS",
          template: {
            subject: "Surprise! Bonus loyalty points just for you",
            body: "We've added 50 bonus loyalty points to your account as a thank you for being amazing! Use them on your next order.",
          },
          status: "PENDING",
        },
        {
          id: "champion_4",
          type: "PERSONAL_OUTREACH",
          title: "Feedback & Co-Creation Invite",
          description:
            "Personally invite top champions to provide product feedback or vote on upcoming designs. This builds emotional investment in your brand.",
          channel: "email",
          priority: "LOW",
          timing: "WITHIN_14_DAYS",
          template: {
            subject: "We'd love your input on what's next",
            body: "As one of our most valued customers, your opinion matters. We'd love for you to vote on our next product launch or share what you'd like to see from us.",
          },
          status: "PENDING",
        },
      ],
    };
  }

  private static buildHighValuePlan(
    segment: any,
    count: number,
    avgLtv: number,
    avgEng: number,
  ): ActionPlanData {
    return {
      segmentId: segment.id,
      segmentType: "HIGH_VALUE",
      name: `High-Value Customer Retention Campaign`,
      description: `${count} high-value customers averaging $${avgLtv.toFixed(0)} LTV. Maximize retention and upsell opportunities.`,
      priority: "HIGH",
      status: "DRAFT",
      isAutoGenerated: true,
      estimatedImpact: {
        revenueUplift: "10-20%",
        customerRetention: "90%+",
        engagement: "Medium-High",
      },
      actions: [
        {
          id: "highvalue_1",
          type: "EMAIL_CAMPAIGN",
          title: "Personalized Product Recommendations",
          description:
            "Send curated product recommendations based on purchase history. High-value customers respond well to personalization.",
          channel: "email",
          priority: "HIGH",
          timing: "IMMEDIATE",
          template: {
            subject: "Picked just for you — new arrivals you'll love",
            body: "Based on your recent purchases, we think you'll love these new arrivals. Shop your personalized picks now with free shipping on orders over $50.",
          },
          status: "PENDING",
        },
        {
          id: "highvalue_2",
          type: "DISCOUNT_OFFER",
          title: "Exclusive Free Shipping Offer",
          description:
            "Offer free shipping for 7 days to incentivize the next purchase. High-value customers are already committed — lower the friction.",
          channel: "both",
          priority: "HIGH",
          timing: "WITHIN_3_DAYS",
          template: {
            subject: "Free shipping is on us — 7 days only!",
            body: "Enjoy free shipping on your next order this week. No minimum, no code needed. Our way of saying thanks!",
            discountType: "FREE_SHIPPING",
          },
          status: "PENDING",
        },
        {
          id: "highvalue_3",
          type: "LOYALTY_REWARD",
          title: "Loyalty Tier Upgrade Incentive",
          description:
            "Show customers how close they are to the next loyalty tier and encourage them to reach it with a double-points weekend.",
          channel: "email",
          priority: "MEDIUM",
          timing: "WITHIN_7_DAYS",
          template: {
            subject: "You're almost at the next level — earn 2x points this weekend!",
            body: "You're just a few points away from unlocking your next reward tier. This weekend, earn double loyalty points on every purchase.",
          },
          status: "PENDING",
        },
        {
          id: "highvalue_4",
          type: "SMS_CAMPAIGN",
          title: "Flash Sale Early Access",
          description:
            "Give high-value customers 24-hour early access to an upcoming sale via SMS. Creates urgency and exclusivity.",
          channel: "sms",
          priority: "MEDIUM",
          timing: "WITHIN_14_DAYS",
          template: {
            body: "🔥 VIP Early Access: Our sale starts for you NOW — 24 hours before everyone else! Shop the best deals first: {link}",
          },
          status: "PENDING",
        },
      ],
    };
  }

  private static buildAtRiskPlan(
    segment: any,
    count: number,
    avgLtv: number,
    avgEng: number,
  ): ActionPlanData {
    return {
      segmentId: segment.id,
      segmentType: "AT_RISK",
      name: `At-Risk Customer Win-Back Strategy`,
      description: `${count} customers at risk of churning. Avg engagement ${avgEng.toFixed(0)}%. Urgent re-engagement needed.`,
      priority: "HIGH",
      status: "DRAFT",
      isAutoGenerated: true,
      estimatedImpact: {
        revenueUplift: "5-15%",
        customerRetention: "30-50% recovery",
        engagement: "Critical",
      },
      actions: [
        {
          id: "atrisk_1",
          type: "EMAIL_CAMPAIGN",
          title: "We Miss You — Win-Back Email",
          description:
            "Send a warm, personal email acknowledging their absence. Include a compelling discount to motivate their return.",
          channel: "email",
          priority: "HIGH",
          timing: "IMMEDIATE",
          template: {
            subject: "We miss you! Here's 20% off to welcome you back",
            body: "It's been a while since your last visit, and we miss you! As a thank you for being part of our community, here's an exclusive 20% discount on your next order. Don't let it slip away!",
            discountType: "PERCENTAGE",
            discountValue: 20,
          },
          status: "PENDING",
        },
        {
          id: "atrisk_2",
          type: "SMS_CAMPAIGN",
          title: "SMS Re-Engagement Nudge",
          description:
            "Follow up with a short SMS if the email doesn't get a response within 3 days. SMS has higher open rates for lapsed customers.",
          channel: "sms",
          priority: "HIGH",
          timing: "WITHIN_3_DAYS",
          template: {
            body: "Hey {firstName}, we saved a 20% discount just for you! It expires soon — shop now: {link} Reply STOP to opt out.",
            discountType: "PERCENTAGE",
            discountValue: 20,
          },
          status: "PENDING",
        },
        {
          id: "atrisk_3",
          type: "EMAIL_CAMPAIGN",
          title: "What's New — Product Update Email",
          description:
            "Show at-risk customers what they're missing. Highlight new products, features, or improvements since their last visit.",
          channel: "email",
          priority: "MEDIUM",
          timing: "WITHIN_7_DAYS",
          template: {
            subject: "A lot has changed — come see what's new!",
            body: "Since your last visit, we've added exciting new products and made improvements just for customers like you. Take a look at what's new and rediscover what you love about us.",
          },
          status: "PENDING",
        },
        {
          id: "atrisk_4",
          type: "PERSONAL_OUTREACH",
          title: "Feedback Request to Top At-Risk",
          description:
            "For high-LTV at-risk customers, send a genuine feedback request. Understanding why they left can prevent future churn.",
          channel: "email",
          priority: "LOW",
          timing: "WITHIN_14_DAYS",
          template: {
            subject: "Quick question — how can we do better?",
            body: "We noticed it's been a while and we'd love to hear from you. Was there something we could have done better? Your feedback helps us improve for everyone.",
          },
          status: "PENDING",
        },
      ],
    };
  }

  private static buildEngagedPlan(
    segment: any,
    count: number,
    avgLtv: number,
    avgEng: number,
  ): ActionPlanData {
    return {
      segmentId: segment.id,
      segmentType: "ENGAGED",
      name: `Engaged Customer Conversion Strategy`,
      description: `${count} highly engaged customers (${avgEng.toFixed(0)}% avg engagement). Convert engagement into purchases and loyalty membership.`,
      priority: "MEDIUM",
      status: "DRAFT",
      isAutoGenerated: true,
      estimatedImpact: {
        revenueUplift: "10-15%",
        customerRetention: "80%+",
        engagement: "Already High — maintain",
      },
      actions: [
        {
          id: "engaged_1",
          type: "EMAIL_CAMPAIGN",
          title: "Loyalty Program Enrollment Push",
          description:
            "Encourage engaged non-members to join the loyalty program. They're already active — convert them into committed members.",
          channel: "email",
          priority: "HIGH",
          timing: "IMMEDIATE",
          template: {
            subject: "You're already earning love — now earn rewards too!",
            body: "You've been an active part of our community, and we want to reward you for it! Join our loyalty program and start earning points on every purchase. Sign up today and get 25 bonus points.",
          },
          status: "PENDING",
        },
        {
          id: "engaged_2",
          type: "DISCOUNT_OFFER",
          title: "Cross-Sell Product Bundle",
          description:
            "Offer a curated bundle of complementary products at a slight discount. Engaged customers are receptive to cross-sell offers.",
          channel: "email",
          priority: "MEDIUM",
          timing: "WITHIN_3_DAYS",
          template: {
            subject: "Complete the set — 10% off when you bundle",
            body: "Love what you've bought? Complete your collection with these perfectly paired items and save 10% when you buy 2 or more.",
            discountType: "PERCENTAGE",
            discountValue: 10,
          },
          status: "PENDING",
        },
        {
          id: "engaged_3",
          type: "SMS_CAMPAIGN",
          title: "Limited-Time Flash Deal",
          description:
            "Send a time-sensitive offer to capitalize on high engagement. Creates urgency for the purchase decision.",
          channel: "sms",
          priority: "MEDIUM",
          timing: "WITHIN_7_DAYS",
          template: {
            body: "🚀 Flash Deal! 15% off for the next 24 hours — just for our most active fans. Use code FLASH15: {link}",
            discountType: "PERCENTAGE",
            discountValue: 15,
          },
          status: "PENDING",
        },
        {
          id: "engaged_4",
          type: "EMAIL_CAMPAIGN",
          title: "Social Proof & UGC Invite",
          description:
            "Invite engaged customers to share reviews, photos, or stories. Builds community and generates valuable user-generated content.",
          channel: "email",
          priority: "LOW",
          timing: "WITHIN_14_DAYS",
          template: {
            subject: "Share your story — get featured + earn rewards",
            body: "We love seeing how you use our products! Share a photo or review and you could be featured on our page — plus earn bonus loyalty points for every review.",
          },
          status: "PENDING",
        },
      ],
    };
  }

  private static buildNewCustomerPlan(
    segment: any,
    count: number,
    avgLtv: number,
    avgEng: number,
  ): ActionPlanData {
    return {
      segmentId: segment.id,
      segmentType: "NEW",
      name: `New Customer Onboarding & Activation`,
      description: `${count} new customers to nurture. First 30 days are critical for building long-term relationships and repeat purchases.`,
      priority: "MEDIUM",
      status: "DRAFT",
      isAutoGenerated: true,
      estimatedImpact: {
        revenueUplift: "5-10%",
        customerRetention: "60-75%",
        engagement: "Building",
      },
      actions: [
        {
          id: "new_1",
          type: "EMAIL_CAMPAIGN",
          title: "Welcome Series — Brand Story",
          description:
            "Send a warm welcome email introducing your brand story, values, and what makes you special. First impressions set the tone.",
          channel: "email",
          priority: "HIGH",
          timing: "IMMEDIATE",
          template: {
            subject: "Welcome to the family! Here's our story 💛",
            body: "We're thrilled to have you! Here's a little about who we are and why we do what we do. We can't wait for you to explore everything we have to offer.",
          },
          status: "PENDING",
        },
        {
          id: "new_2",
          type: "DISCOUNT_OFFER",
          title: "Second Purchase Incentive",
          description:
            "Encourage the crucial second purchase with a targeted discount. The second purchase dramatically increases lifetime value.",
          channel: "both",
          priority: "HIGH",
          timing: "WITHIN_3_DAYS",
          template: {
            subject: "Your next order is 15% off — just for new members",
            body: "Thanks for your first order! Here's 15% off your next purchase to help you discover more of what we have to offer.",
            discountType: "PERCENTAGE",
            discountValue: 15,
          },
          status: "PENDING",
        },
        {
          id: "new_3",
          type: "SMS_CAMPAIGN",
          title: "SMS Opt-In & Welcome Offer",
          description:
            "Encourage new customers to opt in to SMS notifications with a small incentive. SMS subscribers have higher retention rates.",
          channel: "sms",
          priority: "MEDIUM",
          timing: "WITHIN_7_DAYS",
          template: {
            body: "Welcome to {brand}! 🎉 Stay in the loop for exclusive deals and early access. Reply YES to get a $5 off code for your next order!",
            discountType: "FIXED_AMOUNT",
            discountValue: 5,
          },
          status: "PENDING",
        },
        {
          id: "new_4",
          type: "LOYALTY_REWARD",
          title: "Loyalty Program Introduction",
          description:
            "Introduce the loyalty program with an enrollment bonus. Early enrollment leads to higher long-term engagement.",
          channel: "email",
          priority: "MEDIUM",
          timing: "WITHIN_14_DAYS",
          template: {
            subject: "Start earning rewards — join our loyalty program!",
            body: "Did you know every purchase earns you points toward free products and exclusive perks? Join our loyalty program today and get 25 starter points — on us!",
          },
          status: "PENDING",
        },
      ],
    };
  }

  private static buildFrequentBuyerPlan(
    segment: any,
    count: number,
    avgLtv: number,
    avgEng: number,
  ): ActionPlanData {
    return {
      segmentId: segment.id,
      segmentType: "FREQUENT",
      name: `Frequent Buyer Upsell & Retention`,
      description: `${count} frequent buyers with avg LTV $${avgLtv.toFixed(0)}. Focus on increasing average order value and maintaining purchase frequency.`,
      priority: "MEDIUM",
      status: "DRAFT",
      isAutoGenerated: true,
      estimatedImpact: {
        revenueUplift: "10-20%",
        customerRetention: "85%+",
        engagement: "High",
      },
      actions: [
        {
          id: "frequent_1",
          type: "DISCOUNT_OFFER",
          title: "Volume Discount / Bundle Offer",
          description:
            "Offer a volume-based discount to increase average order value. Frequent buyers are responsive to 'buy more, save more' deals.",
          channel: "email",
          priority: "HIGH",
          timing: "IMMEDIATE",
          template: {
            subject: "Buy more, save more — up to 20% off bundles!",
            body: "As one of our most loyal shoppers, enjoy exclusive bundle pricing: Buy 2, save 10%. Buy 3+, save 20%. Mix and match your favorites!",
            discountType: "PERCENTAGE",
            discountValue: 20,
          },
          status: "PENDING",
        },
        {
          id: "frequent_2",
          type: "EMAIL_CAMPAIGN",
          title: "New Arrivals First Look",
          description:
            "Give frequent buyers first access to new products. Their purchase history makes them ideal early adopters.",
          channel: "email",
          priority: "MEDIUM",
          timing: "WITHIN_3_DAYS",
          template: {
            subject: "Just dropped — see it before everyone else 👀",
            body: "You're always ahead of the curve, so we're giving you the first look at our newest arrivals. Shop the collection before it goes live to everyone else.",
          },
          status: "PENDING",
        },
        {
          id: "frequent_3",
          type: "SMS_CAMPAIGN",
          title: "Restock Reminder",
          description:
            "Remind frequent buyers when it's time to reorder based on their purchase cycle. Timely reminders prevent them from shopping elsewhere.",
          channel: "sms",
          priority: "MEDIUM",
          timing: "WITHIN_7_DAYS",
          template: {
            body: "Hey {firstName}! Based on your last order, it might be time to restock. Order now and get free shipping: {link} 📦",
          },
          status: "PENDING",
        },
        {
          id: "frequent_4",
          type: "LOYALTY_REWARD",
          title: "Surprise Reward Milestone",
          description:
            "Surprise frequent buyers with an unexpected reward or bonus points to reinforce their buying behavior and delight them.",
          channel: "both",
          priority: "LOW",
          timing: "WITHIN_14_DAYS",
          template: {
            subject: "A little surprise just for you! 🎁",
            body: "You've been such an amazing customer, we wanted to surprise you with 100 bonus loyalty points! Keep shopping and earning — great rewards are waiting.",
          },
          status: "PENDING",
        },
      ],
    };
  }

  // ──────────────────────────────────────────────
  // ACTION MANAGEMENT
  // ──────────────────────────────────────────────

  /**
   * Update a single action's status within a plan
   */
  static async updateActionStatus(
    planId: string,
    actionId: string,
    status: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "SKIPPED",
    campaignId?: string,
  ): Promise<void> {
    const plan = await prisma.actionPlan.findUnique({
      where: { id: planId },
    });

    if (!plan) throw new Error("Action plan not found");

    const actions = (plan.actions as ActionItem[]) || [];
    const updatedActions = actions.map((action) => {
      if (action.id === actionId) {
        return {
          ...action,
          status,
          campaignId: campaignId || action.campaignId,
          completedAt:
            status === "COMPLETED" ? new Date().toISOString() : action.completedAt,
        };
      }
      return action;
    });

    const completed = updatedActions.filter(
      (a) => a.status === "COMPLETED",
    ).length;

    // Determine plan status
    let planStatus = plan.status;
    if (completed === updatedActions.length) {
      planStatus = "COMPLETED";
    } else if (
      updatedActions.some(
        (a) => a.status === "IN_PROGRESS" || a.status === "COMPLETED",
      )
    ) {
      planStatus = "ACTIVE";
    }

    await prisma.actionPlan.update({
      where: { id: planId },
      data: {
        actions: updatedActions as any,
        actionsCompleted: completed,
        status: planStatus,
      },
    });
  }

  /**
   * Activate a plan — sets status from DRAFT to ACTIVE
   */
  static async activatePlan(planId: string): Promise<void> {
    await prisma.actionPlan.update({
      where: { id: planId },
      data: { status: "ACTIVE" },
    });
  }

  /**
   * Pause a plan
   */
  static async pausePlan(planId: string): Promise<void> {
    await prisma.actionPlan.update({
      where: { id: planId },
      data: { status: "PAUSED" },
    });
  }

  /**
   * Get all plans for an organization
   */
  static async getPlansForOrganization(organizationId: string) {
    return prisma.actionPlan.findMany({
      where: { organizationId },
      include: {
        segment: {
          select: {
            id: true,
            name: true,
            segmentType: true,
            customerCount: true,
            avgLifetimeValue: true,
            avgEngagement: true,
          },
        },
      },
      orderBy: [
        { priority: "asc" }, // HIGH first
        { generatedAt: "desc" },
      ],
    });
  }

  /**
   * Get a single plan by ID
   */
  static async getPlanById(planId: string) {
    return prisma.actionPlan.findUnique({
      where: { id: planId },
      include: {
        segment: {
          select: {
            id: true,
            name: true,
            segmentType: true,
            customerCount: true,
            avgLifetimeValue: true,
            avgEngagement: true,
          },
        },
      },
    });
  }

  /**
   * Delete a plan
   */
  static async deletePlan(planId: string): Promise<void> {
    await prisma.actionPlan.delete({
      where: { id: planId },
    });
  }
}
