"use client";

import { useState, useEffect } from "react";
import Link from "next/link";

interface ActionItem {
  id: string;
  type: string;
  title: string;
  description: string;
  channel: string;
  priority: string;
  timing: string;
  template: {
    subject?: string;
    body: string;
    discountType?: string;
    discountValue?: number;
  };
  status: string;
  campaignId?: string | null;
  completedAt?: string | null;
}

interface ActionPlan {
  id: string;
  segmentId: string;
  name: string;
  description: string;
  actions: ActionItem[];
  status: string;
  priority: string;
  actionsCompleted: number;
  actionsTotal: number;
  estimatedImpact: {
    revenueUplift: string;
    customerRetention: string;
    engagement: string;
  };
  isAutoGenerated: boolean;
  generatedAt: string;
  segment: {
    id: string;
    name: string;
    segmentType: string;
    customerCount: number;
    avgLifetimeValue: number;
    avgEngagement: number;
  };
}

const segmentIcons: Record<string, string> = {
  CHAMPION: "🏆",
  HIGH_VALUE: "💎",
  AT_RISK: "⚠️",
  ENGAGED: "⭐",
  NEW: "🌱",
  FREQUENT: "🔄",
};

const priorityColors: Record<string, string> = {
  HIGH: "bg-red-100 text-red-800",
  MEDIUM: "bg-yellow-100 text-yellow-800",
  LOW: "bg-green-100 text-green-800",
};

const statusColors: Record<string, string> = {
  DRAFT: "bg-gray-100 text-gray-800",
  ACTIVE: "bg-blue-100 text-blue-800",
  COMPLETED: "bg-green-100 text-green-800",
  PAUSED: "bg-yellow-100 text-yellow-800",
};

const actionTypeIcons: Record<string, string> = {
  EMAIL_CAMPAIGN: "📧",
  SMS_CAMPAIGN: "📱",
  DISCOUNT_OFFER: "🏷️",
  LOYALTY_REWARD: "🎁",
  PERSONAL_OUTREACH: "🤝",
};

const timingLabels: Record<string, string> = {
  IMMEDIATE: "Execute immediately",
  WITHIN_3_DAYS: "Within 3 days",
  WITHIN_7_DAYS: "Within 1 week",
  WITHIN_14_DAYS: "Within 2 weeks",
};

export default function ActionPlansPage() {
  const [plans, setPlans] = useState<ActionPlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [expandedPlan, setExpandedPlan] = useState<string | null>(null);
  const [banner, setBanner] = useState<{
    type: "success" | "error";
    message: string;
  } | null>(null);

  useEffect(() => {
    fetchPlans();
  }, []);

  async function fetchPlans() {
    try {
      const res = await fetch("/api/action-plans");
      if (res.ok) {
        const data = await res.json();
        setPlans(data);
      }
    } catch (error) {
      console.error("Failed to fetch action plans:", error);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate() {
    setGenerating(true);
    setBanner(null);
    try {
      const res = await fetch("/api/action-plans", { method: "POST" });
      const data = await res.json();
      if (res.ok) {
        setBanner({
          type: "success",
          message: `${data.generated} new plans generated, ${data.updated} updated based on current segments.`,
        });
        await fetchPlans();
      } else {
        setBanner({ type: "error", message: data.error || "Generation failed" });
      }
    } catch (error) {
      setBanner({ type: "error", message: "Failed to generate action plans" });
    } finally {
      setGenerating(false);
    }
  }

  async function handlePlanStatus(planId: string, status: string) {
    try {
      const res = await fetch(`/api/action-plans/${planId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      });
      if (res.ok) {
        await fetchPlans();
      }
    } catch (error) {
      console.error("Failed to update plan:", error);
    }
  }

  async function handleActionStatus(
    planId: string,
    actionId: string,
    actionStatus: string,
  ) {
    try {
      const res = await fetch(`/api/action-plans/${planId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ actionId, actionStatus }),
      });
      if (res.ok) {
        await fetchPlans();
      }
    } catch (error) {
      console.error("Failed to update action:", error);
    }
  }

  async function handleDeletePlan(planId: string) {
    if (!confirm("Delete this action plan?")) return;
    try {
      const res = await fetch(`/api/action-plans/${planId}`, {
        method: "DELETE",
      });
      if (res.ok) {
        await fetchPlans();
      }
    } catch (error) {
      console.error("Failed to delete plan:", error);
    }
  }

  if (loading) {
    return (
      <div className="p-6">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-gray-200 rounded w-1/3" />
          <div className="h-32 bg-gray-200 rounded" />
          <div className="h-32 bg-gray-200 rounded" />
        </div>
      </div>
    );
  }

  const activePlans = plans.filter((p) => p.status === "ACTIVE");
  const draftPlans = plans.filter((p) => p.status === "DRAFT");
  const completedPlans = plans.filter((p) => p.status === "COMPLETED");
  const totalActions = plans.reduce((sum, p) => sum + p.actionsTotal, 0);
  const completedActions = plans.reduce(
    (sum, p) => sum + p.actionsCompleted,
    0,
  );

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            AI Action Plans
          </h1>
          <p className="text-gray-500 mt-1">
            Auto-generated marketing strategies based on customer segmentation
            results
          </p>
        </div>
        <div className="flex gap-3">
          <Link
            href="/dashboard/segments"
            className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 text-sm"
          >
            ← Back to Segments
          </Link>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="px-4 py-2 bg-indigo-600 text-white text-sm rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {generating ? "Generating..." : "🔄 Generate Action Plans"}
          </button>
        </div>
      </div>

      {/* Banner */}
      {banner && (
        <div
          className={`p-4 rounded-lg ${
            banner.type === "success"
              ? "bg-green-50 text-green-800 border border-green-200"
              : "bg-red-50 text-red-800 border border-red-200"
          }`}
        >
          {banner.message}
        </div>
      )}

      {/* Summary Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <p className="text-sm text-gray-500">Total Plans</p>
          <p className="text-2xl font-bold mt-1">{plans.length}</p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <p className="text-sm text-gray-500">Active</p>
          <p className="text-2xl font-bold text-blue-600 mt-1">
            {activePlans.length}
          </p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <p className="text-sm text-gray-500">Actions Completed</p>
          <p className="text-2xl font-bold text-green-600 mt-1">
            {completedActions}/{totalActions}
          </p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <p className="text-sm text-gray-500">Completion Rate</p>
          <p className="text-2xl font-bold mt-1">
            {totalActions > 0
              ? Math.round((completedActions / totalActions) * 100)
              : 0}
            %
          </p>
        </div>
      </div>

      {/* No Plans State */}
      {plans.length === 0 && (
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center">
          <div className="text-5xl mb-4">📋</div>
          <h3 className="text-lg font-semibold text-gray-900">
            No Action Plans Yet
          </h3>
          <p className="text-gray-500 mt-2 max-w-md mx-auto">
            Click &quot;Generate Action Plans&quot; to analyze your customer
            segments and create tailored marketing strategies automatically.
          </p>
          <p className="text-gray-400 text-sm mt-3">
            Make sure you've run segmentation first (
            <Link
              href="/dashboard/segments"
              className="text-indigo-600 hover:underline"
            >
              Segments Dashboard
            </Link>
            )
          </p>
        </div>
      )}

      {/* How It Works — show when no plans */}
      {plans.length === 0 && (
        <div className="bg-indigo-50 rounded-xl border border-indigo-100 p-6">
          <h3 className="font-semibold text-indigo-900 mb-3">
            How AI Action Plans Work
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 text-sm">
            <div className="flex items-start gap-2">
              <span className="text-lg">1️⃣</span>
              <div>
                <p className="font-medium text-indigo-900">AI Segmentation</p>
                <p className="text-indigo-700">
                  Customers are analyzed using RFM scoring, engagement, LTV, and
                  churn risk
                </p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-lg">2️⃣</span>
              <div>
                <p className="font-medium text-indigo-900">Plan Generation</p>
                <p className="text-indigo-700">
                  Tailored action plans are created for each segment with
                  specific campaigns
                </p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-lg">3️⃣</span>
              <div>
                <p className="font-medium text-indigo-900">Review & Activate</p>
                <p className="text-indigo-700">
                  Review suggested actions, customize if needed, then activate
                  the plan
                </p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-lg">4️⃣</span>
              <div>
                <p className="font-medium text-indigo-900">Execute & Track</p>
                <p className="text-indigo-700">
                  Execute each action step-by-step and track completion progress
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Plans List */}
      {plans.length > 0 && (
        <div className="space-y-4">
          {plans.map((plan) => (
            <div
              key={plan.id}
              className="bg-white rounded-xl border border-gray-200 overflow-hidden"
            >
              {/* Plan Header */}
              <div
                className="p-5 cursor-pointer hover:bg-gray-50 transition"
                onClick={() =>
                  setExpandedPlan(expandedPlan === plan.id ? null : plan.id)
                }
              >
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-3">
                    <span className="text-2xl">
                      {segmentIcons[plan.segment?.segmentType || ""] || "📋"}
                    </span>
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="font-semibold text-gray-900">
                          {plan.name}
                        </h3>
                        <span
                          className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                            statusColors[plan.status] || statusColors.DRAFT
                          }`}
                        >
                          {plan.status}
                        </span>
                        <span
                          className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                            priorityColors[plan.priority] ||
                            priorityColors.MEDIUM
                          }`}
                        >
                          {plan.priority} priority
                        </span>
                      </div>
                      <p className="text-sm text-gray-500 mt-1">
                        {plan.description}
                      </p>
                      <div className="flex items-center gap-4 mt-2 text-xs text-gray-400">
                        <span>
                          {plan.segment?.customerCount || 0} customers
                        </span>
                        <span>
                          Avg LTV: $
                          {(plan.segment?.avgLifetimeValue || 0).toFixed(0)}
                        </span>
                        <span>
                          {plan.actionsCompleted}/{plan.actionsTotal} actions
                          done
                        </span>
                        {plan.isAutoGenerated && (
                          <span className="text-indigo-500">
                            🤖 AI Generated
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {/* Progress bar */}
                    <div className="w-24 h-2 bg-gray-200 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-indigo-500 rounded-full transition-all"
                        style={{
                          width: `${
                            plan.actionsTotal > 0
                              ? (plan.actionsCompleted / plan.actionsTotal) *
                                100
                              : 0
                          }%`,
                        }}
                      />
                    </div>
                    <span className="text-xs text-gray-500">
                      {plan.actionsTotal > 0
                        ? Math.round(
                            (plan.actionsCompleted / plan.actionsTotal) * 100,
                          )
                        : 0}
                      %
                    </span>
                    <svg
                      className={`w-5 h-5 text-gray-400 transition-transform ${
                        expandedPlan === plan.id ? "rotate-180" : ""
                      }`}
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </div>
                </div>
              </div>

              {/* Expanded Details */}
              {expandedPlan === plan.id && (
                <div className="border-t border-gray-200">
                  {/* Impact Estimates */}
                  {plan.estimatedImpact && (
                    <div className="px-5 py-3 bg-gradient-to-r from-indigo-50 to-purple-50 flex flex-wrap gap-6 text-sm">
                      <div>
                        <span className="text-gray-500">Revenue Uplift:</span>{" "}
                        <span className="font-semibold text-indigo-700">
                          {plan.estimatedImpact.revenueUplift}
                        </span>
                      </div>
                      <div>
                        <span className="text-gray-500">Retention:</span>{" "}
                        <span className="font-semibold text-indigo-700">
                          {plan.estimatedImpact.customerRetention}
                        </span>
                      </div>
                      <div>
                        <span className="text-gray-500">Engagement:</span>{" "}
                        <span className="font-semibold text-indigo-700">
                          {plan.estimatedImpact.engagement}
                        </span>
                      </div>
                    </div>
                  )}

                  {/* Actions List */}
                  <div className="p-5 space-y-3">
                    <h4 className="text-sm font-semibold text-gray-700 uppercase tracking-wide">
                      Action Steps
                    </h4>
                    {(plan.actions as ActionItem[]).map(
                      (action, idx) => (
                        <div
                          key={action.id}
                          className={`border rounded-lg p-4 ${
                            action.status === "COMPLETED"
                              ? "bg-green-50 border-green-200"
                              : action.status === "SKIPPED"
                                ? "bg-gray-50 border-gray-200 opacity-60"
                                : action.status === "IN_PROGRESS"
                                  ? "bg-blue-50 border-blue-200"
                                  : "bg-white border-gray-200"
                          }`}
                        >
                          <div className="flex items-start justify-between">
                            <div className="flex items-start gap-3">
                              <span className="text-lg mt-0.5">
                                {actionTypeIcons[action.type] || "📌"}
                              </span>
                              <div>
                                <div className="flex items-center gap-2">
                                  <span className="text-xs text-gray-400 font-mono">
                                    #{idx + 1}
                                  </span>
                                  <h5 className="font-medium text-gray-900">
                                    {action.title}
                                  </h5>
                                  <span
                                    className={`px-1.5 py-0.5 rounded text-xs ${
                                      priorityColors[action.priority] ||
                                      "bg-gray-100 text-gray-600"
                                    }`}
                                  >
                                    {action.priority}
                                  </span>
                                </div>
                                <p className="text-sm text-gray-600 mt-1">
                                  {action.description}
                                </p>
                                <div className="flex items-center gap-3 mt-2 text-xs text-gray-400">
                                  <span>
                                    Channel:{" "}
                                    {action.channel === "both"
                                      ? "📧 Email + 📱 SMS"
                                      : action.channel === "email"
                                        ? "📧 Email"
                                        : "📱 SMS"}
                                  </span>
                                  <span>
                                    ⏱️ {timingLabels[action.timing] || action.timing}
                                  </span>
                                  {action.template.discountType && (
                                    <span>
                                      🏷️{" "}
                                      {action.template.discountType ===
                                      "PERCENTAGE"
                                        ? `${action.template.discountValue}% off`
                                        : action.template.discountType ===
                                            "FIXED_AMOUNT"
                                          ? `$${action.template.discountValue} off`
                                          : "Free Shipping"}
                                    </span>
                                  )}
                                </div>

                                {/* Template Preview */}
                                <div className="mt-3 text-xs bg-gray-50 rounded p-3 border border-gray-100">
                                  {action.template.subject && (
                                    <p className="text-gray-500 mb-1">
                                      <strong>Subject:</strong>{" "}
                                      {action.template.subject}
                                    </p>
                                  )}
                                  <p className="text-gray-600">
                                    {action.template.body}
                                  </p>
                                </div>

                                {action.completedAt && (
                                  <p className="text-xs text-green-600 mt-2">
                                    ✅ Completed{" "}
                                    {new Date(
                                      action.completedAt,
                                    ).toLocaleDateString()}
                                  </p>
                                )}
                              </div>
                            </div>

                            {/* Action Controls */}
                            <div className="flex flex-col gap-1 ml-4 shrink-0">
                              {action.status === "PENDING" && (
                                <>
                                  <button
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      handleActionStatus(
                                        plan.id,
                                        action.id,
                                        "COMPLETED",
                                      );
                                    }}
                                    className="px-3 py-1 bg-green-600 text-white text-xs rounded hover:bg-green-700"
                                  >
                                    ✓ Done
                                  </button>
                                  <button
                                    onClick={(e) => {
                                      e.stopPropagation();
                                      handleActionStatus(
                                        plan.id,
                                        action.id,
                                        "SKIPPED",
                                      );
                                    }}
                                    className="px-3 py-1 border border-gray-300 text-gray-600 text-xs rounded hover:bg-gray-50"
                                  >
                                    Skip
                                  </button>
                                </>
                              )}
                              {action.status === "COMPLETED" && (
                                <span className="text-green-600 text-xs font-medium">
                                  ✅ Done
                                </span>
                              )}
                              {action.status === "SKIPPED" && (
                                <button
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleActionStatus(
                                      plan.id,
                                      action.id,
                                      "PENDING",
                                    );
                                  }}
                                  className="px-3 py-1 border border-gray-300 text-gray-500 text-xs rounded hover:bg-gray-50"
                                >
                                  Undo Skip
                                </button>
                              )}
                            </div>
                          </div>
                        </div>
                      ),
                    )}
                  </div>

                  {/* Plan Controls */}
                  <div className="border-t border-gray-200 px-5 py-3 bg-gray-50 flex items-center justify-between">
                    <div className="flex gap-2">
                      {plan.status === "DRAFT" && (
                        <button
                          onClick={() => handlePlanStatus(plan.id, "ACTIVE")}
                          className="px-4 py-1.5 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700"
                        >
                          ▶️ Activate Plan
                        </button>
                      )}
                      {plan.status === "ACTIVE" && (
                        <button
                          onClick={() => handlePlanStatus(plan.id, "PAUSED")}
                          className="px-4 py-1.5 bg-yellow-500 text-white text-sm rounded-lg hover:bg-yellow-600"
                        >
                          ⏸️ Pause Plan
                        </button>
                      )}
                      {plan.status === "PAUSED" && (
                        <button
                          onClick={() => handlePlanStatus(plan.id, "ACTIVE")}
                          className="px-4 py-1.5 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700"
                        >
                          ▶️ Resume Plan
                        </button>
                      )}
                    </div>
                    <div className="flex gap-2">
                      <Link
                        href={`/dashboard/segments/${plan.segmentId}`}
                        className="px-3 py-1.5 border border-gray-300 text-gray-700 text-sm rounded-lg hover:bg-gray-100"
                      >
                        View Segment
                      </Link>
                      <button
                        onClick={() => handleDeletePlan(plan.id)}
                        className="px-3 py-1.5 border border-red-300 text-red-600 text-sm rounded-lg hover:bg-red-50"
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
